# Название твоего сайта
title: MusicX

# Краткое описание
description: Мощный, быстрый и красивый неофициальный плеер для прослушивания музыки из ВКонтакте.

# Указываем GitHub, что мы используем свои стили, и просим не применять стандартные темы Jekyll
theme: null

# Разрешаем загрузку папки с картинками (на всякий случай, чтобы Jekyll её не проигнорировал)
include:
  - src/images

# Исключаем системные файлы или исходники, которые не нужны на готовом сайте (по желанию)
exclude:
  - README.md
